name: otayori_calendar
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.2+4

environment:
  sdk: '>=3.4.0 <4.0.0' # Flutter 3.22以降の推奨SDKバージョン

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_riverpod: ^2.5.1
  table_calendar: ^3.1.1
  shared_preferences: ^2.2.3
  flutter_local_notifications: ^17.1.2
  google_generative_ai: ^0.4.0
  image_picker: ^1.1.2
  intl: ^0.20.2 
  flutter_dotenv: ^5.1.0
  path_provider: ^2.1.3
  path: ^1.9.0
  cunning_document_scanner: ^1.1.2
  uuid: ^4.4.0
  flutter_colorpicker: ^1.0.3
  google_mobile_ads: ^5.1.0
  firebase_core: ^3.1.1
  firebase_crashlytics: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  generate: true
  uses-material-design: true
  assets:
    - .env

flutter_launcher_icons:
  android: true
  image_path: "assets/icon/icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon/icon.png"